server:
  port: 8000

eureka:
  clint:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: first-service # 라우터 식별자
          uri: lb://MY-FIRST-SERVICE # 연결해줄 service-location. 실제 호출하려는 서비스의 이름이나 ID
          predicates: # 라우팅의 조건
            - Path=/first-service/**
        - id: second-service
          uri: lb://MY-SECOND-SERVICE
          predicates:
            - Path=/second-service/**